<?php 
require_once('connect.php');
//require_once('selects.php');

// $file = fopen("likprod.csv", "r");

// while(!feof($file)){
// 	$w = fgetcsv($file, 1024, ';');

//  //    echo '<pre>';
// 	// var_dump($w);

// 	$result = $connect->query("INSERT INTO `likproducts` (`code`, `name`, `price`, `purchase`) VALUES ('{$w[0]}','{$w[1]}','{$w[2]}','{$w[3]}')");

// 	if ( $result == true )
//   {
//   echo "<p>Запись добавлена</p>";
//   }
//   else
//   {
//   echo "<p>Запись не добавлена: ".mysqli_error($connect)."</p>";
//   }
// }
// fclose($file);

//$tableName = 'users_statistic';
//// Get JSON file and decode contents into PHP arrays/values
//$jsonFile = 'users_statistic.json';
//$jsonData = json_decode(file_get_contents($jsonFile), true);
//
//// Iterate through JSON and build INSERT statements
//foreach ($jsonData as $id=>$row) {
//    $insertPairs = array();
//    foreach ($row as $key=>$val) {
//        $insertPairs[addslashes($key)] = addslashes($val);
//    }
//    $insertKeys = '`' . implode('`,`', array_keys($insertPairs)) . '`';
//    $insertVals = '"' . implode('","', array_values($insertPairs)) . '"';
//
////    echo "INSERT INTO `{$tableName}` ({$insertKeys}) VALUES ({$insertVals});" . "\n";
//    $insert = $connect->query("INSERT INTO `{$tableName}` ({$insertKeys}) VALUES ({$insertVals})");
//}

?>

<!DOCTYPE html>
<html>
<head>
	<title></title>

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

	<link rel="stylesheet" type="text/css" href="../public/css/main.css">

	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
	<script type="text/javascript" src="js/main.js"></script>

</head>
<body>

<!--	<div class="main-content">-->
<!---->
<!--		<div class="content">-->
<!---->
<!--				<nav class="navbar navbar-expand-lg navbar-light bg-light">-->
<!--			 -->
<!--			  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">-->
<!--			    <span class="navbar-toggler-icon"></span>-->
<!--			  </button>-->
<!---->
<!--			  <div class="collapse navbar-collapse" id="navbarSupportedContent">-->
<!--			    <ul class="navbar-nav mr-auto">-->
<!--			      <li class="nav-item active">-->
<!--			        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>-->
<!--			      </li>-->
<!--			      <li class="nav-item">-->
<!--			        <a class="nav-link" href="#">Link</a>-->
<!--			      </li>-->
<!--			      <li class="nav-item dropdown">-->
<!--			        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
<!--			          Dropdown-->
<!--			        </a>-->
<!--			        <div class="dropdown-menu" aria-labelledby="navbarDropdown">-->
<!--			          <a class="dropdown-item" href="#">Action</a>-->
<!--			          <a class="dropdown-item" href="#">Another action</a>-->
<!--			          <div class="dropdown-divider"></div>-->
<!--			          <a class="dropdown-item" href="#">Something else here</a>-->
<!--			        </div>-->
<!--			      </li>-->
<!--			      <li class="nav-item">-->
<!--			        <a class="nav-link disabled" href="#">Disabled</a>-->
<!--			      </li>-->
<!--			    </ul>-->
<!--			    <form class="form-inline my-2 my-lg-0">-->
<!--			      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">-->
<!--			      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>-->
<!--			    </form>-->
<!--			  </div>-->
<!--			</nav>-->
<!---->
<!--				<table class="table table-striped">-->
<!--			  <thead>-->
<!--			    <tr>-->
<!--			      <th scope="col">id</th>-->
<!--			      <th scope="col">Артикул</th>-->
<!--			      <th scope="col">Наименование</th>-->
<!--			      <th scope="col">Цена</th>-->
<!--			      <th scope="col">Действие</th>-->
<!--			    </tr>-->
<!--			  </thead>-->
<!--			  <tbody>-->
<!--			  	--><?php //foreach ($shares as $value):?><!-- -->
<!--			    <tr>-->
<!--			      <th scope="row">--><?//=$value['id']?><!--</th>-->
<!--			      <td>--><?//=$value['code'];?><!--</td>-->
<!--			      <td>--><?//=$value['name'];?><!--</td>-->
<!--			      <td>--><?//=$value['price'];?><!--</td>-->
<!--			      <td>-->
<!--			      	<button type="button" class="btn btn-outline-dark" data-toggle="modal" data-target="#edit">Обновить</button>-->
<!--			      </td>-->
<!--			    </tr>-->
<!--			    --><?php //endforeach;?>
<!--			  </tbody>-->
<!--			</table>-->
<!--		</div>-->
<!--	</div>-->

</body>
</html>

<!-- Modal -->
					<div class="modal fade" id="edit" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
					  <div class="modal-dialog" role="document">
					    <div class="modal-content">
					      <div class="modal-header">
					        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
					        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
					          <span aria-hidden="true">&times;</span>
					        </button>
					      </div>
					      <div class="modal-body">
					        ...
					      </div>
					      <div class="modal-footer">
					        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
					        <button type="button" class="btn btn-primary">Save changes</button>
					      </div>
					    </div>
					  </div>
					</div>